#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, in3,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, in4,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, in5,    armSensor,      sensorPotentiometer)
#pragma config(Sensor, in6,    lightSensor,    sensorNone)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop, reversed, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port4,           neckMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex269, openLoop, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task checkIfStopped()
{
	while(true){
		if(vexRT[Btn8U] == 1)
		{
			StopAllTasks();
		}
	}
}
task drive()
{
	while(true)
	{
		while(SensorValue(sonarSensor) > 60 || SensorValue(sonarSensor) == -1)
		{
			motor[rightMotor] = 60;
			motor[leftMotor] = 60;
		}
		while(SensorValue(sonarSensor) < 60)
		{
			motor[rightMotor] = -60;
			motor[leftMotor] = 60;

			if(SensorValue(sonarSensor) > 60 || SensorValue(sonarSensor) == -1)
			{
				break;
			}
		}
	}
}
task checkLightSensor()
{
	while(true){
		if(SensorValue(lightSensor) > 250)
		{
			StopAllTasks();
		}
	}
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	StartTask(checkIfStopped);
	StartTask(drive);
	StartTask(checkLightSensor);
 	while(true){}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
